#!/usr/bin/env python3
"""
Step 3 of 3 -- build_single_file.py

Collapse src/ into one self-contained HTML document:

    src/fonts.css              -> <style>, @font-face url()s as base64 data URIs
    src/styles.css             -> <style>, verbatim
    src/offline_overrides.css  -> <style>, verbatim
    src/script.js              -> <script>, verbatim
    src/fonts/*.woff2          -> inlined as base64
    upstream_raw/logo.png      -> 32x32 favicon, inlined as a data URI

Cascade order is preserved exactly: fonts, upstream styles, overrides. Nothing
in styles.css or script.js is rewritten, minified or reordered -- they go in as
the same bytes the live site serves, which is what keeps behaviour identical.

The script asserts the result is genuinely self-contained and fails loudly if it
is not. Re-running produces a byte-identical file (no timestamps embedded), so
git diffs stay meaningful.

Usage:
    python tools/build_single_file.py
"""

from __future__ import annotations

import base64
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
RAW = ROOT / "upstream_raw"
OUT = ROOT / "BAII_Plus_Financial_Calculator_Offline_2026.html"

BANNER = """<!--
  BA II Plus Financial Calculator -- offline single-file edition
  =============================================================
  Source:      https://baiiplusfinancialcalculator.com/
  Contains:    the calculator widget only. Navbar, "other calculators"
               carousel, marketing sections, footer, ads and analytics from the
               original page have all been removed.
  Self-contained: stylesheet, script and webfonts are inlined below. No network
               access of any kind is required or attempted.

  styles.css and script.js are the upstream files, byte-for-byte. The only
  authored CSS is offline_overrides.css (vertical centring, mobile padding).

  Generated by tools/build_single_file.py -- do not edit this file by hand.
  Edit src/ and rebuild.
-->
"""


def b64_fonts(css: str) -> tuple[str, int]:
    """Replace url(fonts/x.woff2) with base64 data URIs. Returns (css, bytes_inlined)."""
    total = 0

    def sub(m: re.Match[str]) -> str:
        nonlocal total
        name = m.group(1)
        path = SRC / "fonts" / name
        if not path.is_file():
            raise SystemExit(f"ERROR: {path.relative_to(ROOT)} not found")
        data = path.read_bytes()
        total += len(data)
        return f"url(data:font/woff2;base64,{base64.b64encode(data).decode('ascii')})"

    css = re.sub(r"url\(fonts/([^)\s]+\.woff2)\)", sub, css)
    if "url(fonts/" in css:
        raise SystemExit("ERROR: a local font url() survived inlining")
    return css, total


def favicon() -> str:
    """Downscale the site logo to a 32x32 PNG data URI."""
    try:
        from PIL import Image
    except ImportError:
        print("  note   Pillow missing, skipping favicon")
        return ""
    with Image.open(RAW / "logo.png") as im:
        im = im.convert("RGBA")
        im.thumbnail((32, 32), Image.LANCZOS)
        buf = io.BytesIO()
        im.save(buf, format="PNG", optimize=True)
    png = buf.getvalue()
    print(f"  icon   favicon from logo.png, {len(png):,} bytes")
    return (
        '<link rel="icon" type="image/png" href="data:image/png;base64,'
        + base64.b64encode(png).decode("ascii")
        + '" />'
    )


def main() -> int:
    page = (SRC / "page.html").read_text(encoding="utf-8")

    # --- stylesheets, in cascade order -----------------------------------
    sheets = []
    for name in ("fonts.css", "styles.css", "offline_overrides.css"):
        css = (SRC / name).read_text(encoding="utf-8")
        if name == "fonts.css":
            css, n = b64_fonts(css)
            print(f"  inline src/{name}  ({n:,} bytes of woff2 -> base64)")
        print(f"  inline src/{name}  ({len(css):,} chars)")
        sheets.append((name, css))

    # --- swap every <link rel=stylesheet> for a <style> block ------------
    order = iter(sheets)

    def repl_link(m: re.Match[str]) -> str:
        name, css = next(order)
        return f'<style data-source="{name}">\n{css}\n</style>'

    page, n_links = re.subn(
        r'<link\s+rel="stylesheet"\s+href="[^"]+"\s*/?>', repl_link, page
    )
    if n_links != len(sheets):
        raise SystemExit(
            f"ERROR: expected {len(sheets)} stylesheet links in page.html, replaced {n_links}"
        )

    # --- swap the <script src> for an inline <script> ---------------------
    script = (SRC / "script.js").read_text(encoding="utf-8")
    page, n_scripts = re.subn(
        r'<script\s+src="[^"]+"\s*>\s*</script>',
        lambda m: '<script data-source="script.js">\n' + script + "\n</script>",
        page,
    )
    if n_scripts != 1:
        raise SystemExit(f"ERROR: expected 1 script tag in page.html, replaced {n_scripts}")
    print(f"  inline src/script.js  ({len(script):,} chars)")

    # --- favicon + provenance banner -------------------------------------
    icon = favicon()
    if icon:
        page = page.replace("<title>", icon + "\n<title>", 1)
    page = page.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + BANNER, 1)

    # --- assertions: the result must be genuinely offline ----------------
    # Scanned against comments-stripped text, because provenance notes mention
    # the source URL and that loads nothing. What matters is whether any
    # *resource-loading* reference points outside the document.
    scannable = re.sub(r"<!--.*?-->", "", page, flags=re.S)
    scannable = re.sub(r"/\*.*?\*/", "", scannable, flags=re.S)

    problems = []
    # No <link> or <script> may still point at a file; a data: URI is self-contained
    # (the favicon uses one) so it is not a violation.
    for m in re.finditer(r'<(?:link|script)\b[^>]*\b(?:href|src)="([^"]*)"', scannable):
        if not m.group(1).startswith("data:"):
            problems.append(f"<link>/<script> still loads an external file: {m.group(1)}")
    for m in re.finditer(r'(?:src|href)="([^"]*)"', scannable):
        url = m.group(1)
        if not url.startswith(("data:", "#")):
            problems.append(f"non-inline resource reference: {url}")
    for m in re.finditer(r"url\(([^)]*)\)", scannable):
        target = m.group(1).strip().strip("'\"")
        if not target.startswith("data:"):
            problems.append(f"CSS url() not inlined: {target}")

    widget = re.search(r'<div[^>]*id="calculator"', page)
    if not widget:
        problems.append("calculator widget missing from output")

    if problems:
        for p in problems:
            print(f"ERROR: {p}", file=sys.stderr)
        return 1

    # newline="\n" is deliberate: the default translates \n to os.linesep, so a
    # Windows build would emit CRLF and a Linux build LF, producing different
    # bytes and a different file size for identical inputs. Forcing LF keeps the
    # output byte-reproducible on every platform.
    OUT.write_text(page, encoding="utf-8", newline="\n")
    size = OUT.stat().st_size
    print(f"\nWrote {OUT.name}  ({size:,} bytes / {size / 1024:.1f} KiB)")
    print("Self-contained: no external links, no external scripts, no font fetches.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
